/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ajuda.java
 *
 * Created on 02/09/2011, 22:52:44
 */
package sudoku;

/**
 *
 * @author Usuario
 */
public class Ajuda extends javax.swing.JFrame {

    /** Creates new form Ajuda */
    public Ajuda() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txf_doc = new javax.swing.JTextArea();
        btn_fecha = new javax.swing.JButton();

        setTitle("Ajuda");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        txf_doc.setColumns(20);
        txf_doc.setRows(5);
        txf_doc.setText("Neste jogo, você começa com um tabuleiro de dimensões\nm x m parcialmente preenchido. A cada passo do jogo você\n pode preencher as posições vazias com um número entre\n1 e m. A solução para o jogo é um tabuleiro completamente \npreenchido no qual cada número de 1 a m apareça apenas\numa vez em cada linha, coluna e bloco.");
        txf_doc.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txf_doc.setEnabled(false);
        jScrollPane1.setViewportView(txf_doc);

        btn_fecha.setText("Fechar");
        btn_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btn_fecha)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_fecha)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fechaActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_btn_fechaActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        this.setVisible(false);
    }//GEN-LAST:event_formWindowLostFocus


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_fecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txf_doc;
    // End of variables declaration//GEN-END:variables
}
